apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range-argo
spec:
  limits:
  - default:
      cpu: 200m
      memory: 500Mi
    defaultRequest:
      cpu: 70m
      memory: 70Mi
    type: Container
