apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-argo
  annotations:
    workflows.argoproj.io/description: |
       This resource quota prevents using limited cpu and ram in a namespace edited.
spec:
  hard:
    count/workflows.argoproj.io: "100"
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "3"
    limits.memory: "8Gi"
