apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range-argo
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1000Mi
    defaultRequest:
      cpu: 300m
      memory: 400Mi
    type: Container
