apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range-argo
spec:
  limits:
  - default:
      cpu: 4000m
      memory: 6000Mi
    defaultRequest:
      cpu: 2000m
      memory: 3000Mi
    type: Container
