apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range-argo
spec:
  limits:
  - default:
      cpu: 0.1
      memory: "100Mi"
    defaultRequest:
      cpu: 0.07
      memory: "70Mi"
    type: Container
