apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range-argo
spec:
  limits:
  - default:
      cpu: 100m
      memory: 200Mi
    defaultRequest:
      cpu: 70m
      memory: 70Mi
    type: Container
