apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-argo
  annotations:
    workflows.argoproj.io/description: |
       This resource quota prevents using limited cpu and ram in a namespace.

