apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-argo
  annotations:
    workflows.argoproj.io/description: |
       This resource quota prevents using limited cpu and ram in a namespace edited.
spec:
  hard:
    workflows.argoproj.io/requests.cpu: 2
    workflows.argoproj.io/requests.memory: "2Gi"
    workflows.argoproj.io/limits.cpu: 3
    workflows.argoproj.io/limits.memory: "3Gi"
